# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import model_pb2 as model__pb2


class ModelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.predict = channel.unary_unary(
                '/Model/predict',
                request_serializer=model__pb2.modelRequest.SerializeToString,
                response_deserializer=model__pb2.Empty.FromString,
                )
        self.sendPrediction = channel.unary_stream(
                '/Model/sendPrediction',
                request_serializer=model__pb2.Empty.SerializeToString,
                response_deserializer=model__pb2.modelAnswer.FromString,
                )
        self.publishMetrics = channel.unary_unary(
                '/Model/publishMetrics',
                request_serializer=model__pb2.metricsJson.SerializeToString,
                response_deserializer=model__pb2.Empty.FromString,
                )
        self.registerModel = channel.unary_unary(
                '/Model/registerModel',
                request_serializer=model__pb2.Empty.SerializeToString,
                response_deserializer=model__pb2.modelDefinition.FromString,
                )


class ModelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendPrediction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def publishMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def registerModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'predict': grpc.unary_unary_rpc_method_handler(
                    servicer.predict,
                    request_deserializer=model__pb2.modelRequest.FromString,
                    response_serializer=model__pb2.Empty.SerializeToString,
            ),
            'sendPrediction': grpc.unary_stream_rpc_method_handler(
                    servicer.sendPrediction,
                    request_deserializer=model__pb2.Empty.FromString,
                    response_serializer=model__pb2.modelAnswer.SerializeToString,
            ),
            'publishMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.publishMetrics,
                    request_deserializer=model__pb2.metricsJson.FromString,
                    response_serializer=model__pb2.Empty.SerializeToString,
            ),
            'registerModel': grpc.unary_unary_rpc_method_handler(
                    servicer.registerModel,
                    request_deserializer=model__pb2.Empty.FromString,
                    response_serializer=model__pb2.modelDefinition.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Model', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Model(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Model/predict',
            model__pb2.modelRequest.SerializeToString,
            model__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sendPrediction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Model/sendPrediction',
            model__pb2.Empty.SerializeToString,
            model__pb2.modelAnswer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def publishMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Model/publishMetrics',
            model__pb2.metricsJson.SerializeToString,
            model__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def registerModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Model/registerModel',
            model__pb2.Empty.SerializeToString,
            model__pb2.modelDefinition.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
