# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\"1\n\x0btaskRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\x12\x11\n\tsessionID\x18\x02 \x01(\t\"0\n\x0bmodelAnswer\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x11\n\tsessionID\x18\x02 \x01(\t\"O\n\x11modelRequirements\x12\x12\n\nneeds_text\x18\x01 \x01(\x08\x12\x13\n\x0bneeds_image\x18\x02 \x01(\x08\x12\x11\n\tsessionID\x18\x03 \x01(\t\"1\n\x0btaskMetrics\x12\x11\n\tsessionID\x18\x01 \x01(\t\x12\x0f\n\x07metrics\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\xab\x01\n\x0btaskService\x12)\n\tstartTask\x12\x06.Empty\x1a\x12.modelRequirements0\x01\x12!\n\x07runTask\x12\x06.Empty\x1a\x0c.taskRequest0\x01\x12$\n\nfinishTask\x12\x06.Empty\x1a\x0c.taskMetrics0\x01\x12(\n\x10getModelResponse\x12\x0c.modelAnswer\x1a\x06.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TASKREQUEST']._serialized_start=15
  _globals['_TASKREQUEST']._serialized_end=64
  _globals['_MODELANSWER']._serialized_start=66
  _globals['_MODELANSWER']._serialized_end=114
  _globals['_MODELREQUIREMENTS']._serialized_start=116
  _globals['_MODELREQUIREMENTS']._serialized_end=195
  _globals['_TASKMETRICS']._serialized_start=197
  _globals['_TASKMETRICS']._serialized_end=246
  _globals['_EMPTY']._serialized_start=248
  _globals['_EMPTY']._serialized_end=255
  _globals['_TASKSERVICE']._serialized_start=258
  _globals['_TASKSERVICE']._serialized_end=429
# @@protoc_insertion_point(module_scope)
